# Generated by Django 2.2.4 on 2019-09-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('short_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='LongURL',
        ),
        migrations.DeleteModel(
            name='ShortURL',
        ),
    ]
