# Generated by Django 2.2.4 on 2019-09-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_auto_20190901_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.CharField(max_length=8),
        ),
    ]
