# Generated by Django 2.2.4 on 2019-09-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_auto_20190901_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='long_url',
            field=models.URLField(max_length=256),
        ),
    ]
