# Generated by Django 2.2.4 on 2019-09-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0004_auto_20190901_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
